name: Generate Website Pages

# Workflow'un ne zaman çalışacağını belirler:
on:
  push:
    branches:
      - main # Sadece 'main' branch'ine push yapıldığında çalışır (branch adını değiştirin gerekirse)
  workflow_dispatch: # Manuel olarak tetikleme imkanı sunar (Actions sekmesinden)


# Workflow'un repoya yazma izni olması için gerekli
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Çalıştırılacak sanal makine tipi
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4 # Repodaki kodları çalışma alanına çeker

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Kullanılacak Python sürümü (script'inize uygun seçin)

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow # Gerekli kütüphaneyi kur

      - name: Run Website Generator Script
        run: python generate_site.py # Güncellenmiş Python script'ini çalıştırır (dosya adını kontrol edin)

      - name: Commit and Push Generated Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated generation of website pages [skip ci]" # Commit mesajı
          # [skip ci] ifadesi, bu commit'in tekrar workflow'u tetiklemesini engeller
          commit_user_name: github-actions[bot] # Commit yapan kullanıcı adı
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com # Commit yapan e-posta
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> # Commit yazarı
          # Sadece değişiklik varsa commit atılacaktır
